### ISSUE TITLE
Docker can't find the telegram-upload.json

### ISSUE THREAD

**Issue by simonlkch** [Nekmo/telegram-upload#146]
* telegram-upload version: Docker version
* Python version: Docker version
* Operating System: Docker version(Window)

### Description

i try to use the docker compose to use the telegram-upload
i mount the volume config directory.
after compose up, the bash said that "Please enter api_id: go to xxxxxxxxxxx"

![image](https://user-images.githubusercontent.com/3492546/152491018-d50157db-00e3-4328-9a29-00a62dcad71f.png)

here is my file structure
Please noted that the telegram-upload.json is not created automatically, i put it manually

telegram-upload-docker
 - config
    - telegram-upload.json
 - files
    - test.txt
 - docker-compose.yml

And here is my docker-compose.yml

```
version: '3.3'
services:
    telegram-upload-docker:
        volumes:
            - './files:\files'
            - './config:\config'
        image: nekmo/telegram-upload:master
        command: upload test.txt --to me
```

telegram-upload.json
the file contain api_id and the api_hash value with real value
```
{"api_id": 99999, "api_hash": "abcdefg123456789789456123"}

```
