### ISSUE TITLE
Feature request - Support `--interactive` flag for Docker usage

### ISSUE THREAD

**Issue by KiritaniAyaka** [Nekmo/telegram-upload#212]
* telegram-upload version:
* Python version:
* Operating System:
* Dependencies list (run `pip freeze`):

I'm using this Docker Image [`nekmo/telegram-upload:master` (e2aac998aa98) ](https://hub.docker.com/layers/nekmo/telegram-upload/master/images/sha256-e2aac998aa98d4cca7a98f0b3d3bc7e272f485b475e7f603b3fa75a79d30c874?context=explore)

### Description

It looks like the usage via Docker doesn't support `--interactive` flag, cloud you add support for it?

### What I Did

I use Docker Compose to run it, below is the content of docker-compose.yml

```yml
version: '3'

services:
  tg-dl:
    image: nekmo/telegram-upload:master
    container_name: telegram-upload
    tty: true
    stdin_open: true
    volumes:
       - ./files:/files
       - ./config:/config
```

Run `docker compose run tg-dl download -i -f <username>` or using `--interactive` instead of `-i`

I got an error: `Error: No such option: --interactive` or `Error: No such option: -i`

Then I checked the outputs of `docker compose run tg-dl download --help`. It looks like doesn't support this flag.

Could you add support for it? I think it will be an excellent change
